services:
  iso8583-simulator:
    container_name: iso8583-simulator
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./ISO8583-Simulator:/app
    command: python3 start.py
    restart: always
    ports:
      - "9218:9218"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  tigerbeetle:
    image: ghcr.io/tigerbeetle/tigerbeetle:0.16.66
    container_name: tb-cluster
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_NICE
    entrypoint: /bin/sh
    command:
      - -c
      - |
        if [ ! -f /data/cluster.tigerbeetle ]; then
          /tigerbeetle format --development --cluster=0 --replica=0 --replica-count=1 /data/cluster.tigerbeetle
        fi
        exec /tigerbeetle start --development --addresses=0.0.0.0:5555 /data/cluster.tigerbeetle
    ports:
      - "5555:5555"
      - "5555:5555/udp"
    volumes:
      - tb-data:/data

volumes:
  tb-data:
