export const SALES_RESPONSE_CODES = [
  { req: '00', res: '00', desc: 'Approved or completed successfully' },
  { req: '01', res: '01', desc: 'Refer to card issuer' },
  { req: '02', res: '02', desc: "Refer to card issuer's special conditions" },
  { req: '03', res: '03', desc: 'Invalid merchant' },
  { req: '04', res: '04', desc: 'Pick-up' },
  { req: '05', res: '05', desc: 'Do not honor' },
  { req: '06', res: '06', desc: 'Error' },
  { req: '07', res: '07', desc: 'Pick-up card, special condition' },
  { req: '08', res: '08', desc: 'Honour with identification' },
  { req: '09', res: '09', desc: 'Request in progress' },
  { req: '10', res: '10', desc: 'Approved for partial amount' },
  { req: '11', res: '11', desc: 'Approved (VIP)' },
  { req: '12', res: '12', desc: 'Invalid transaction' },
  { req: '13', res: '13', desc: 'Invalid amount' },
  { req: '14', res: '14', desc: 'Invalid card number (no such number)' },
  { req: '15', res: '15', desc: 'No such issuer' },
  { req: '16', res: '16', desc: 'Approved, update track 3' },
  { req: '17', res: '17', desc: 'Customer cancellation' },
  { req: '18', res: '18', desc: 'Customer dispute' },
  { req: '19', res: '19', desc: 'Re-enter transaction' },
  { req: '20', res: '20', desc: 'Invalid response' },
  { req: '21', res: '21', desc: 'No action taken' },
  { req: '22', res: '22', desc: 'Suspected malfunction' },
  { req: '23', res: '23', desc: 'Unacceptable transaction fee' },
  { req: '24', res: '24', desc: 'File update not supported by receiver' },
  { req: '25', res: '25', desc: 'Unable to locate record on file' },
  { req: '26', res: '26', desc: 'Duplicate file update record, old record replaced' },
  { req: '27', res: '27', desc: 'File update field edit error' },
  { req: '28', res: '28', desc: 'File update file locked out' },
  { req: '29', res: '29', desc: 'File update not successful, contact acquirer' },
  { req: '30', res: '30', desc: 'Format error' },
  { req: '31', res: '31', desc: 'Bank not supported by switch' },
  { req: '32', res: '32', desc: 'Completed partially' },
  { req: '33', res: '33', desc: 'Expired card' },
  { req: '34', res: '34', desc: 'Suspected fraud' },
  { req: '35', res: '35', desc: 'Card acceptor contact acquirer' },
  { req: '36', res: '36', desc: 'Restricted card' },
  { req: '37', res: '37', desc: 'Card acceptor call acquirer security' },
  { req: '38', res: '38', desc: 'Allowable PIN tries exceeded' },
  { req: '39', res: '39', desc: 'No credit account' },
  { req: '40', res: '40', desc: 'Requested function not supported' },
  { req: '41', res: '41', desc: 'Lost card' },
  { req: '42', res: '42', desc: 'No universal account' },
  { req: '43', res: '43', desc: 'Stolen card, pick-up' },
  { req: '44', res: '44', desc: 'No investment account' },
  { req: '51', res: '51', desc: 'Not sufficient funds' },
  { req: '52', res: '52', desc: 'No checking account' },
  { req: '53', res: '53', desc: 'No savings account' },
  { req: '54', res: '54', desc: 'Expired card' },
  { req: '55', res: '55', desc: 'Incorrect personal identification number' },
  { req: '56', res: '56', desc: 'No card record' },
  { req: '57', res: '57', desc: 'Transaction not permitted to cardholder' },
  { req: '58', res: '58', desc: 'Transaction not permitted to terminal' },
  { req: '59', res: '59', desc: 'Suspected fraud' },
  { req: '60', res: '60', desc: 'Card acceptor contact acquirer' },
  { req: '61', res: '61', desc: 'Exceeds withdrawal amount limit' },
  { req: '62', res: '62', desc: 'Restricted card' },
  { req: '63', res: '63', desc: 'Security violation' },
  { req: '64', res: '64', desc: 'Original amount incorrect' },
  { req: '65', res: '65', desc: 'Exceeds withdrawal frequency limit' },
  { req: '66', res: '66', desc: "Card acceptor call acquirer's security department" },
  { req: '67', res: '67', desc: 'Hard capture (card must be picked up)' },
  { req: '68', res: '68', desc: 'Response received too late' },
  { req: '75', res: '75', desc: 'Allowable number of PIN tries exceeded' },
  { req: '78', res: '78', desc: 'Card not activated' },
  { req: '80', res: '80', desc: 'Credit issuer unavailable' },
  { req: '82', res: '82', desc: 'Invalid expiration date or CVV/CVN mismatch' },
  { req: '85', res: '85', desc: 'Success: address verification' },
  { req: '90', res: '90', desc: 'Cutoff in process; retry later' },
  { req: '91', res: '91', desc: 'Issuer or switch is inoperative' },
  { req: '92', res: '92', desc: 'Routing for financial institution not found' },
  { req: '93', res: '93', desc: 'Violation of law; transaction cannot be completed' },
  { req: '94', res: '94', desc: 'Duplicate transmission' },
  { req: '95', res: '95', desc: 'Reconcile error' },
  { req: '96', res: '96', desc: 'System malfunction' },
  { req: '97', res: '97', desc: 'Reserved for national use' },
  { req: '98', res: '98', desc: 'Reserved for national use' },
  { req: '99', res: '99', desc: 'Reserved for national use' },
] as const;
